"""Computer Networks GATE Question Bank."""

QUESTIONS = [
    {
        "id": "cn_subnet_001",
        "subject": "Computer Networks",
        "topic": "Network Layer & IP Addressing",
        "subtopic": "IPv4 Addressing & CIDR Subnetting",
        "concept": "Subnet mask and number of usable host addresses in CIDR block",
        "type": "NAT",
        "marks": 2,
        "difficulty": "gate",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "An organization is allocated the IP block 200.10.20.0/24. The administrator divides this block into 8 equal subnets. What is the MAXIMUM number of USABLE host IP addresses in EACH subnet?",
        "options": None,
        "answer": "30",
        "msq_answers": None,
        "explanation": "1. Base block: /24 (8 host bits).\n2. Number of subnets = 8 = 2^3 ⟹ 3 bits borrowed for subnetting.\n3. New subnet prefix = 24 + 3 = /27.\n4. Number of host bits remaining = 32 - 27 = 5 bits.\n5. Total IP addresses per subnet = 2^5 = 32.\n6. Usable host addresses = 2^5 - 2 = 32 - 2 = 30 (subtracting Network ID and Directed Broadcast Address).",
        "gate_trap": "Always subtract 2 for the Network address and Directed Broadcast address when asked for USABLE hosts.",
        "key_concept": "Usable hosts per subnet = 2^(32 − prefix_length) − 2.",
        "reference_url": "https://www.geeksforgeeks.org/introduction-to-subnetting/"
    },
    {
        "id": "cn_tcp_001",
        "subject": "Computer Networks",
        "topic": "Transport Layer",
        "subtopic": "TCP Congestion Control (Slow Start, AIMD, Fast Retransmit)",
        "concept": "TCP Reno congestion window progression across RTTs",
        "type": "NAT",
        "marks": 2,
        "difficulty": "gate",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "In a TCP Reno connection, the Slow-Start Threshold (ssthresh) is initially 32 KB and the Maximum Segment Size (MSS) is 2 KB. The congestion window (cwnd) starts at 2 KB (1 MSS). Assume no packet loss occurs for the first 6 RTTs. What is the size of the congestion window (in KB) at the END of the 6th RTT?",
        "options": None,
        "answer": "36",
        "msq_answers": None,
        "explanation": "Let's trace cwnd after each RTT:\n- Start: cwnd = 2 KB (1 MSS).\n- RTT 1 (Slow Start): cwnd doubles ⟹ 4 KB (2 MSS).\n- RTT 2 (Slow Start): cwnd doubles ⟹ 8 KB (4 MSS).\n- RTT 3 (Slow Start): cwnd doubles ⟹ 16 KB (8 MSS).\n- RTT 4 (Slow Start): cwnd doubles ⟹ 32 KB (16 MSS) [ssthresh reached!].\n- RTT 5 (Congestion Avoidance): cwnd increases by 1 MSS (2 KB) ⟹ 34 KB.\n- RTT 6 (Congestion Avoidance): cwnd increases by 1 MSS (2 KB) ⟹ 36 KB.\nAt the end of the 6th RTT, cwnd = 36 KB.",
        "gate_trap": "Once cwnd reaches ssthresh (32 KB at RTT 4), TCP switches from Exponential growth (Slow Start) to Linear growth (Congestion Avoidance: +1 MSS per RTT).",
        "key_concept": "Slow Start doubles cwnd every RTT until ssthresh; Congestion Avoidance adds 1 MSS per RTT (AIMD additive increase).",
        "reference_url": "https://www.geeksforgeeks.org/tcp-congestion-control/"
    },
    {
        "id": "cn_csmacd_001",
        "subject": "Computer Networks",
        "topic": "Data Link Layer",
        "subtopic": "CSMA/CD & Minimum Frame Size Calculation",
        "concept": "Minimum frame length calculation in CSMA/CD to detect collisions",
        "type": "NAT",
        "marks": 2,
        "difficulty": "gate",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "A 1 km long 100 Mbps CSMA/CD network has a signal propagation speed of 2 * 10^8 m/s. What is the MINIMUM frame size (in bytes) required for reliable collision detection?",
        "options": None,
        "answer": "125",
        "msq_answers": None,
        "explanation": "In CSMA/CD, the transmission time must be at least twice the propagation delay:\nTransmission Time (Tt) >= 2 * Propagation Delay (Tp)\n1. Tp = Distance / Velocity = 1000 m / (2 * 10^8 m/s) = 5 * 10^(-6) seconds = 5 microseconds.\n2. Minimum Tt = 2 * Tp = 2 * 5 us = 10 microseconds = 10 * 10^(-6) s.\n3. Minimum Frame Size = Bandwidth * Tt = (100 * 10^6 bits/s) * (10 * 10^(-6) s) = 1000 bits.\n4. In bytes = 1000 / 8 = 125 bytes.",
        "gate_trap": "Remember that Tt >= 2 * Tp (Round Trip Time) so the sender can detect collisions before completing frame transmission.",
        "key_concept": "CSMA/CD Minimum Frame Size: L_min = 2 * Tp * Bandwidth = 2 * (Distance / Velocity) * Bandwidth.",
        "reference_url": "https://www.geeksforgeeks.org/csma-cd-carrier-sense-multiple-access-with-collision-detection/"
    }
]
