"""General Aptitude (GA) GATE Question Bank (Verbal, Quant, Analytical, Spatial)."""

QUESTIONS = [
    {
        "id": "ga_quant_001",
        "subject": "General Aptitude",
        "topic": "Quantitative Aptitude",
        "subtopic": "Ratios & Percentages",
        "concept": "Successive percentage change and profit calculation",
        "type": "NAT",
        "marks": 1,
        "difficulty": "medium",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "The price of an item is increased by 25% and subsequently decreased by 20%. What is the NET PERCENTAGE CHANGE in the original price of the item? (Enter 0 if unchanged, positive for increase, negative for decrease).",
        "options": None,
        "answer": "0",
        "msq_answers": None,
        "explanation": "Let the initial price be P = 100.\n1. After 25% increase: P1 = 100 * (1 + 0.25) = 125.\n2. After 20% decrease: P2 = 125 * (1 - 0.20) = 125 * 0.80 = 100.\nNet change = 100 - 100 = 0% change.",
        "gate_trap": "Percentage increase and decrease do NOT simply cancel out additively (+25 - 20 ≠ +5). The base changes after the first operation.",
        "key_concept": "Net percentage change formula: a + b + (a * b) / 100 = 25 - 20 - (25 * 20)/100 = 5 - 5 = 0%.",
        "reference_url": "https://www.geeksforgeeks.org/successive-percentage-change/"
    },
    {
        "id": "ga_quant_002",
        "subject": "General Aptitude",
        "topic": "Quantitative Aptitude",
        "subtopic": "Powers, Exponents & Logarithms",
        "concept": "Logarithmic base transformation and simplification",
        "type": "NAT",
        "marks": 2,
        "difficulty": "gate",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "If log₂(x) + log₄(x) + log₁₆(x) = 21/4, what is the value of x?",
        "options": None,
        "answer": "8",
        "msq_answers": None,
        "explanation": "Convert all logarithms to base 2:\n- log₄(x) = log₂(x) / log₂(4) = (1/2) * log₂(x)\n- log₁₆(x) = log₂(x) / log₂(16) = (1/4) * log₂(x)\n\nEquation becomes:\nlog₂(x) + (1/2)*log₂(x) + (1/4)*log₂(x) = 21/4\n(1 + 1/2 + 1/4) * log₂(x) = 21/4\n(7/4) * log₂(x) = 21/4\nlog₂(x) = (21/4) * (4/7) = 3\nx = 2^3 = 8.",
        "gate_trap": "Use base change rule: log_{b^k}(x) = (1/k) * log_b(x).",
        "key_concept": "Logarithm base power rule: log_{b^k}(x) = (1/k) * log_b(x).",
        "reference_url": "https://www.geeksforgeeks.org/logarithm-rules-and-properties/"
    },
    {
        "id": "ga_quant_003",
        "subject": "General Aptitude",
        "topic": "Quantitative Aptitude",
        "subtopic": "Permutations & Combinations",
        "concept": "Counting arrangements with restricted positions",
        "type": "NAT",
        "marks": 2,
        "difficulty": "gate",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "In how many ways can 5 boys and 4 girls be seated in a row such that NO two girls sit together?",
        "options": None,
        "answer": "43200",
        "msq_answers": None,
        "explanation": "Gap method for no two girls sitting together:\n1. First arrange the 5 boys in a row: 5! = 120 ways.\n2. In a row of 5 boys, there are 6 available gaps (including ends): _ B1 _ B2 _ B3 _ B4 _ B5 _\n3. Select 4 gaps out of 6 for the 4 girls: 6 C 4 = 15 ways.\n4. Arrange the 4 girls in the selected 4 gaps: 4! = 24 ways.\nTotal arrangements = 5! * (6 C 4) * 4! = 120 * 15 * 24 = 43,200.",
        "gate_trap": "Do not subtract adjacent cases from total when more than 2 items are restricted. Always use the Gap Method.",
        "key_concept": "Gap Method: Arrange unrestricted items first (n!), then place m restricted items into the (n+1) available gaps (P(n+1, m)).",
        "reference_url": "https://www.geeksforgeeks.org/permutations-and-combinations/"
    },
    {
        "id": "ga_verbal_001",
        "subject": "General Aptitude",
        "topic": "Verbal Aptitude",
        "subtopic": "Subject-Verb Agreement",
        "concept": "Subject-verb agreement with correlative conjunctions (neither...nor)",
        "type": "MCQ",
        "marks": 1,
        "difficulty": "easy",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "Choose the most grammatically correct option to complete the sentence:\n\"Neither the professor nor the students ________ able to attend the emergency committee meeting.\"",
        "options": {
            "A": "was",
            "B": "were",
            "C": "is",
            "D": "has been"
        },
        "answer": "B",
        "msq_answers": None,
        "explanation": "In sentences joined by 'neither... nor' or 'either... or', the verb must agree with the closer subject (the subject adjacent to the verb).\nHere, 'the students' is plural and adjacent to the blank, so the plural verb 'were' is required.",
        "gate_trap": "Do not default to the first subject ('the professor'); with 'neither...nor', the verb agrees with the proximate (closer) subject.",
        "key_concept": "Rule of Proximity: In 'Neither A nor B', the verb agrees in number with subject B.",
        "reference_url": "https://www.geeksforgeeks.org/subject-verb-agreement-rules/"
    },
    {
        "id": "ga_verbal_002",
        "subject": "General Aptitude",
        "topic": "Verbal Aptitude",
        "subtopic": "Vocabulary & Words in Context",
        "concept": "Contextual word selection and nuances of meaning",
        "type": "MCQ",
        "marks": 1,
        "difficulty": "medium",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "Select the word that best fits the blank:\n\"The researcher's argument was so ________ that none of the reviewers could point out a single flaw in the derivation.\"",
        "options": {
            "A": "specious",
            "B": "lucid",
            "C": "cogent",
            "D": "tenuous"
        },
        "answer": "C",
        "msq_answers": None,
        "explanation": "- 'Cogent' means clear, logical, convincing, and powerfully persuasive, which matches an argument with no flaws.\n- 'Specious' means superficially plausible but actually wrong.\n- 'Tenuous' means very weak or slight.\n- 'Lucid' means clear to understand, but 'cogent' specifically conveys logical soundness and unassailable strength.",
        "gate_trap": "'Specious' is a common distractor that looks positive but means deceitfully plausible.",
        "key_concept": "Cogent: logically forceful and convincing; Specious: falsely attractive or misleading.",
        "reference_url": "https://www.geeksforgeeks.org/vocabulary-words/"
    },
    {
        "id": "ga_analytical_001",
        "subject": "General Aptitude",
        "topic": "Analytical Aptitude",
        "subtopic": "Logic & Syllogisms",
        "concept": "Categorical syllogism and valid deductive conclusions",
        "type": "MCQ",
        "marks": 2,
        "difficulty": "medium",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "Consider the following statements:\n1. All algorithms are programs.\n2. Some programs are bugs.\nWhich of the following conclusions logically follows from the premises?",
        "options": {
            "A": "All algorithms are bugs.",
            "B": "Some bugs are algorithms.",
            "C": "Some bugs are programs.",
            "D": "No algorithm is a bug."
        },
        "answer": "C",
        "msq_answers": None,
        "explanation": "- Statement 2 states: 'Some programs are bugs'. By direct subversion/conversion of an I-type proposition (Some A are B ⟹ Some B are A), 'Some bugs are programs' is definitely TRUE.\n- There is no necessary overlapping connection established between Algorithms and Bugs (the middle term 'programs' is not distributed across both premises). Hence A, B, and D do not necessarily follow.",
        "gate_trap": "Because the middle term 'programs' is undistributed, no definite conclusion can be drawn linking 'Algorithms' directly to 'Bugs'.",
        "key_concept": "Conversion of particular affirmative (I-proposition): 'Some A are B' directly implies 'Some B are A'.",
        "reference_url": "https://www.geeksforgeeks.org/syllogism-reasoning-concepts/"
    },
    {
        "id": "ga_analytical_002",
        "subject": "General Aptitude",
        "topic": "Analytical Aptitude",
        "subtopic": "Seating Arrangements & Blood Relations",
        "concept": "Circular permutation and relative positioning constraints",
        "type": "MCQ",
        "marks": 2,
        "difficulty": "gate",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "Six friends P, Q, R, S, T, and U are sitting around a circular table facing the center.\n- P sits second to the right of T.\n- Q sits opposite to T.\n- R sits immediate left of P.\n- S is not adjacent to T.\nWho is sitting opposite to R?",
        "options": {
            "A": "P",
            "B": "S",
            "C": "U",
            "D": "T"
        },
        "answer": "B",
        "msq_answers": None,
        "explanation": "Let's assign circular positions 1 to 6 clockwise:\n1. Place T at position 1. (Faces center).\n2. Q is opposite to T ⟹ Q is at position 4.\n3. P is second to the right of T (counter-clockwise or rightward facing center) ⟹ Position 5.\n4. R sits immediate left of P (clockwise facing center) ⟹ Position 6.\n5. S is not adjacent to T (so not pos 2 or pos 6) ⟹ S must be at Position 3.\n6. Remaining friend U is at Position 2.\nOpposite pairs in 6-person circle are (pos, pos+3):\n- T (pos 1) ↔ Q (pos 4)\n- U (pos 2) ↔ P (pos 5)\n- S (pos 3) ↔ R (pos 6)\nTherefore, S sits opposite to R.",
        "gate_trap": "When facing the center of a circle, 'right' is counter-clockwise and 'left' is clockwise.",
        "key_concept": "In a 6-person circular table, opposite positions are separated by exactly (6/2) = 3 positions.",
        "reference_url": "https://www.geeksforgeeks.org/circular-seating-arrangement/"
    },
    {
        "id": "ga_spatial_001",
        "subject": "General Aptitude",
        "topic": "Spatial Aptitude",
        "subtopic": "Paper Folding & Paper Cutting",
        "concept": "Rotational symmetry and 2D net visualization of a 3D cube",
        "type": "MCQ",
        "marks": 1,
        "difficulty": "medium",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "A standard 6-sided die is unfolded into a cross-shaped net where the central vertical strip has faces [1, 2, 3, 4] from top to bottom, face 5 is to the left of face 2, and face 6 is to the right of face 2. When folded back into a cube, which face is OPPOSITE to face 2?",
        "options": {
            "A": "Face 1",
            "B": "Face 3",
            "C": "Face 4",
            "D": "Face 6"
        },
        "answer": "C",
        "msq_answers": None,
        "explanation": "In an unfolded cube net:\n- Alternate faces along any straight row or column become opposite faces when folded into a cube.\n- In the vertical strip [1, 2, 3, 4]:\n  Face 1 is opposite to Face 3.\n  Face 2 is opposite to Face 4.\n- The flanking faces (Face 5 on left and Face 6 on right) are opposite to each other.\nTherefore, Face 4 is opposite to Face 2.",
        "gate_trap": "In any straight 1x4 net strip, faces separated by exactly one intervening face are opposite to each other.",
        "key_concept": "Cube Net Rule: In linear strips of net squares, alternate faces (separated by 1 square) are mutually opposite.",
        "reference_url": "https://www.geeksforgeeks.org/cube-and-dice-reasoning/"
    },
    {
        "id": "ga_spatial_002",
        "subject": "General Aptitude",
        "topic": "Spatial Aptitude",
        "subtopic": "Translation & Rotation of Shapes",
        "concept": "2D mirror reflection combined with 90 degree clockwise rotation",
        "type": "MCQ",
        "marks": 1,
        "difficulty": "easy",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "A planar shape in the shape of the letter 'F' is first reflected across a vertical mirror line, and then rotated 90 degrees clockwise in the plane. What does the top horizontal bar of the original 'F' point towards in the final figure?",
        "options": {
            "A": "Upwards",
            "B": "Downwards",
            "C": "Leftwards",
            "D": "Rightwards"
        },
        "answer": "B",
        "msq_answers": None,
        "explanation": "Let's trace the vector of the top bar of 'F':\n1. Originally, the top bar points to the RIGHT (vector: (+1, 0)).\n2. Reflection across vertical mirror reverses the x-coordinate: vector points to the LEFT (vector: (-1, 0)).\n3. Rotating a vector pointing LEFT (-1, 0) by 90 degrees CLOCKWISE rotates it to point DOWNWARDS (vector: (0, -1)).\nTherefore, the bar points downwards.",
        "gate_trap": "Track the orientation vectors step-by-step: Reflection flips the horizontal direction, then 90° clockwise rotation turns Left into Down.",
        "key_concept": "Vertical reflection: (x, y) -> (-x, y). 90° CW rotation: (x, y) -> (y, -x). Combined: (x, y) -> (y, x) -> (-1, 0) becomes (0, -1) [Down].",
        "reference_url": "https://www.geeksforgeeks.org/spatial-aptitude-for-gate/"
    }
]
