"""Operating Systems GATE Question Bank."""

QUESTIONS = [
    {
        "id": "os_proc_001",
        "subject": "Operating Systems",
        "topic": "Processes & Threads",
        "subtopic": "System Calls (fork, exec, wait, exit)",
        "concept": "Counting processes created by nested fork loops",
        "type": "NAT",
        "marks": 2,
        "difficulty": "gate",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "Consider the following C code snippet:\n\nint main() {\n    for (int i = 0; i < 4; i++) {\n        if (fork() == 0) {\n            fork();\n            break;\n        }\n    }\n    return 0;\n}\n\nAssuming all fork() calls succeed, how many TOTAL processes (including the initial parent process) are created during the entire execution?",
        "options": None,
        "answer": "9",
        "msq_answers": None,
        "explanation": "Let's trace iteration by iteration:\n- Initial: 1 process (Parent P0).\n- i=0: P0 forks C1 (child). In C1 (fork()==0), C1 forks GC1 and breaks (now 2 processes from C1). P0 continues.\n- i=1: P0 forks C2. C2 forks GC2 and breaks (2 processes from C2). P0 continues.\n- i=2: P0 forks C3. C3 forks GC3 and breaks (2 processes from C3). P0 continues.\n- i=3: P0 forks C4. C4 forks GC4 and breaks (2 processes from C4). P0 loop ends.\nTotal processes = 1 (P0) + 4 * 2 (each iteration produces 2 processes from child) = 1 + 8 = 9.",
        "gate_trap": "Students often blindly use 2^n formula without noting the 'break' statement inside child branch!",
        "key_concept": "Child process executes fork() then immediately breaks from loop, generating exactly 2 processes per iteration.",
        "reference_url": "https://www.geeksforgeeks.org/fork-system-call/"
    },
    {
        "id": "os_sched_001",
        "subject": "Operating Systems",
        "topic": "CPU Scheduling",
        "subtopic": "Round Robin & Multilevel Queue",
        "concept": "Average waiting time in Round Robin scheduling with arrival times",
        "type": "NAT",
        "marks": 2,
        "difficulty": "gate",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "Three processes P1, P2, P3 arrive at times 0, 1, 2 ms with CPU burst times of 8, 4, 2 ms respectively. The CPU scheduler uses Round Robin (RR) scheduling with a Time Quantum (TQ) of 3 ms. Assume context switch time is 0. What is the average waiting time of the processes (in ms)?",
        "options": None,
        "answer": "5",
        "msq_answers": None,
        "explanation": "Ready Queue and Gantt Chart:\n- t=0: P1 arrives. P1 runs for [0, 3]. During this, P2 (t=1) and P3 (t=2) arrive. Ready Queue: [P2, P3, P1(rem 5)].\n- t=3: P2 runs for [3, 6] (rem 1). Ready Queue: [P3, P1(5), P2(1)].\n- t=6: P3 runs for [6, 8] (finishes at t=8). Ready Queue: [P1(5), P2(1)].\n- t=8: P1 runs for [8, 11] (rem 2). Ready Queue: [P2(1), P1(2)].\n- t=11: P2 runs for [11, 12] (finishes at t=12). Ready Queue: [P1(2)].\n- t=12: P1 runs for [12, 14] (finishes at t=14).\n\nCompletion Times: P1=14, P2=12, P3=8.\nTurnaround Time (CT - AT): P1 = 14 - 0 = 14, P2 = 12 - 1 = 11, P3 = 8 - 2 = 6.\nWaiting Time (TAT - BT): P1 = 14 - 8 = 6, P2 = 11 - 4 = 7, P3 = 6 - 2 = 4.\nAverage Waiting Time = (6 + 7 + 4) / 3 = 17 / 3 = 5.67 ms (Rounded: 5.67, or 17/3). For integer entry: 5.67.",
        "gate_trap": "Processes arriving while current process is executing must be placed in ready queue before the preempted process is re-added.",
        "key_concept": "Turnaround Time = Completion Time − Arrival Time; Waiting Time = Turnaround Time − Burst Time.",
        "reference_url": "https://www.geeksforgeeks.org/program-round-robin-scheduling-set-1/"
    },
    {
        "id": "os_synch_001",
        "subject": "Operating Systems",
        "topic": "Concurrency & Synchronization",
        "subtopic": "Counting & Binary Semaphores",
        "concept": "Counting semaphore value calculation with concurrent wait and signal operations",
        "type": "MCQ",
        "marks": 1,
        "difficulty": "medium",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "A counting semaphore S is initialized to 12. Then 8 P (wait) operations and 5 V (signal) operations are completed on S. What is the resulting value of S?",
        "options": {
            "A": "9",
            "B": "4",
            "C": "15",
            "D": "8"
        },
        "answer": "A",
        "msq_answers": None,
        "explanation": "Initial value of semaphore S = 12.\nEach P operation decrements S: -8.\nEach V operation increments S: +5.\nFinal value = 12 - 8 + 5 = 9.",
        "gate_trap": "Do not confuse P (Wait/decrement) with V (Signal/increment).",
        "key_concept": "Semaphore invariant: Final Value = Initial Value − (# of successful P operations) + (# of V operations).",
        "reference_url": "https://www.geeksforgeeks.org/semaphores-in-process-synchronization/"
    },
    {
        "id": "os_deadlock_001",
        "subject": "Operating Systems",
        "topic": "Deadlocks",
        "subtopic": "Deadlock Avoidance & Banker's Algorithm",
        "concept": "Safe state and safe sequence determination in Banker's Algorithm",
        "type": "MSQ",
        "marks": 2,
        "difficulty": "gate",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "Which of the following statements regarding Deadlock and Banker's Algorithm is/are TRUE?\n\nSelect all that apply:",
        "options": {
            "A": "If a system is in an unsafe state, it is guaranteed to eventually deadlock.",
            "B": "An unsafe state is not necessarily a deadlocked state, but deadlock cannot occur from a safe state.",
            "C": "Banker's algorithm requires advance knowledge of the maximum resource requirement for each process.",
            "D": "Deadlock prevention algorithms always yield higher CPU resource utilization than deadlock detection algorithms."
        },
        "answer": "B, C",
        "msq_answers": ["B", "C"],
        "explanation": "- A is FALSE: An unsafe state means the system cannot guarantee avoidance of deadlock, but processes might release resources early without requesting max claim, avoiding deadlock.\n- B is TRUE: Deadlocked state ⊂ Unsafe state. A safe state guarantees at least one safe execution sequence, ensuring deadlock freedom.\n- C is TRUE: Banker's algorithm requires apriori maximum claim matrix.\n- D is FALSE: Deadlock prevention is conservative and restricts resource access, often reducing resource utilization.",
        "gate_trap": "Unsafe state does NOT mean deadlock has occurred; it means the system is vulnerable to deadlock if worst-case demands occur.",
        "key_concept": "Safe State ⟹ No Deadlock; Deadlock ⟹ Unsafe State. But Unsafe State ⇏ Deadlock.",
        "reference_url": "https://www.geeksforgeeks.org/bankers-algorithm-in-operating-system-2/"
    },
    {
        "id": "os_mem_001",
        "subject": "Operating Systems",
        "topic": "Memory Management & Virtual Memory",
        "subtopic": "Paging & Multi-Level Page Tables",
        "concept": "Multi-level page table size and virtual address decomposition",
        "type": "NAT",
        "marks": 2,
        "difficulty": "gate",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "A system uses 32-bit virtual addresses and a 2-level paging scheme with 4 KB (2^12 bytes) page size. Each page table entry (PTE) takes 4 bytes. If the first level page table must fit exactly into a single page frame, how many bits are used for the second-level page table index?",
        "options": None,
        "answer": "10",
        "msq_answers": None,
        "explanation": "1. Virtual Address = 32 bits.\n2. Page size = 4 KB = 2^12 bytes ⟹ Page Offset (d) = 12 bits.\n3. Virtual Page Number bits = 32 - 12 = 20 bits (divided into p1 and p2).\n4. Page size = 4096 bytes; Entry size = 4 bytes ⟹ Entries per page = 4096 / 4 = 1024 = 2^10 entries.\n5. Since Level 1 page table fits into 1 page frame, it has 2^10 entries ⟹ p1 = 10 bits.\n6. Level 2 index (p2) = Total VPN bits - p1 = 20 - 10 = 10 bits.",
        "gate_trap": "Remember to subtract the offset bits from 32 before splitting between Level 1 and Level 2!",
        "key_concept": "Entries per page frame = (Page Frame Size) / (PTE Size) = 2^k entries ⟹ k index bits.",
        "reference_url": "https://www.geeksforgeeks.org/multilevel-paging-in-operating-system/"
    },
    {
        "id": "os_mem_002",
        "subject": "Operating Systems",
        "topic": "Memory Management & Virtual Memory",
        "subtopic": "TLB & Effective Memory Access Time",
        "concept": "Effective Memory Access Time (EMAT) calculation with TLB and 2-level paging",
        "type": "NAT",
        "marks": 2,
        "difficulty": "gate",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "In a 2-level paging system, main memory access time is 100 ns and TLB access time is 20 ns. The TLB hit ratio is 90%. Assume that upon a TLB hit, the physical frame number is obtained directly. Upon a TLB miss, both page tables and main memory are accessed. What is the Effective Memory Access Time (in ns)?",
        "options": None,
        "answer": "140",
        "msq_answers": None,
        "explanation": "EMAT Formula for 2-level paging:\n- On TLB Hit: TLB_time + Mem_time = 20 + 100 = 120 ns.\n- On TLB Miss: TLB_time + (2 * Mem_time for 2 PT levels) + Mem_time (for data) = 20 + 200 + 100 = 320 ns.\n- EMAT = (Hit_Ratio * Hit_Time) + ((1 - Hit_Ratio) * Miss_Time)\n  EMAT = (0.90 * 120) + (0.10 * 320) = 108 + 32 = 140 ns.",
        "gate_trap": "In 2-level paging, a TLB miss requires 2 memory accesses for the page tables + 1 memory access for actual data operand = 3 memory accesses!",
        "key_concept": "TLB Miss Time = TLB_time + (k + 1) * Memory_Access_Time for k-level paging.",
        "reference_url": "https://www.geeksforgeeks.org/effective-memory-access-time-in-paging/"
    },
    {
        "id": "os_disk_001",
        "subject": "Operating Systems",
        "topic": "File Systems & Disk Scheduling",
        "subtopic": "Disk Scheduling (FCFS, SSTF, SCAN, C-SCAN, LOOK, C-LOOK)",
        "concept": "Total head movement calculation in SCAN disk scheduling",
        "type": "NAT",
        "marks": 2,
        "difficulty": "medium",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "A disk queue contains requests for I/O to blocks on cylinders: 98, 183, 37, 122, 14, 124, 65, 67. The head is currently at cylinder 53 and moving towards higher cylinders (towards 199). Cylinders are numbered 0 to 199. Using the SCAN algorithm, what is the total head movement (in cylinders)?",
        "options": None,
        "answer": "331",
        "msq_answers": None,
        "explanation": "SCAN (Elevator) algorithm moving towards higher end:\n1. Head starts at 53.\n2. Serves higher requests in increasing order up to the boundary (199):\n   53 -> 65 -> 67 -> 98 -> 122 -> 124 -> 183 -> 199.\n   Movement in this direction = 199 - 53 = 146 cylinders.\n3. Head reverses at 199 and moves down to the smallest request (14):\n   199 -> 37 -> 14.\n   Movement in this direction = 199 - 14 = 185 cylinders.\n4. Total head movement = (199 - 53) + (199 - 14) = 146 + 185 = 331... wait!\nLet's check carefully:\n53 to 199 = 146.\nFrom 199 down to 14 = 199 - 14 = 185.\nTotal = 146 + 185 = 331 cylinders.\nWait, does SCAN go to cylinder 199? YES, SCAN goes all the way to disk end (199), whereas LOOK only goes to the highest request (183).\nFor SCAN: (199 - 53) + (199 - 14) = 331.",
        "gate_trap": "SCAN goes all the way to the disk boundary (199), while LOOK stops at the largest requested cylinder (183).",
        "key_concept": "SCAN Total Head Movement = (Max_Cylinder - Initial_Position) + (Max_Cylinder - Min_Request).",
        "reference_url": "https://www.geeksforgeeks.org/scan-elevator-disk-scheduling-algorithms/"
    }
]
