"""Programming & Data Structures GATE Question Bank."""

QUESTIONS = [
    {
        "id": "ds_tree_001",
        "subject": "Programming & Data Structures",
        "topic": "Non-Linear Data Structures",
        "subtopic": "Binary Trees & Traversals",
        "concept": "Counting total non-isomorphic binary trees with n unlabeled nodes",
        "type": "NAT",
        "marks": 2,
        "difficulty": "gate",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "What is the total number of structurally distinct (unlabeled) binary trees that can be formed with 5 nodes?",
        "options": None,
        "answer": "42",
        "msq_answers": None,
        "explanation": "The number of structurally distinct binary trees with n unlabeled nodes is given by the n-th Catalan number C(n):\nC(n) = (1 / (n + 1)) * (2n C n)\nFor n = 5:\nC(5) = (1 / 6) * (10 C 5) = (1 / 6) * (10 * 9 * 8 * 7 * 6) / (5 * 4 * 3 * 2 * 1) = (1 / 6) * 252 = 42.",
        "gate_trap": "If nodes are LABELED, the answer would be C(n) * n! (42 * 120 = 5040). For UNLABELED nodes, it is simply C(n) = 42.",
        "key_concept": "Unlabeled binary trees count = Catalan number C(n) = (2n)! / ((n+1)! * n!).",
        "reference_url": "https://www.geeksforgeeks.org/total-number-of-possible-binary-search-trees-with-n-keys/"
    },
    {
        "id": "ds_c_ptr_001",
        "subject": "Programming & Data Structures",
        "topic": "Programming in C",
        "subtopic": "Pointers & Pointer Arithmetic",
        "concept": "Multi-dimensional array pointer decay and indexing arithmetic",
        "type": "NAT",
        "marks": 2,
        "difficulty": "gate",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "Consider the following C code segment:\n\n#include <stdio.h>\nint main() {\n    int a[3][4] = {\n        {1, 2, 3, 4},\n        {5, 6, 7, 8},\n        {9, 10, 11, 12}\n    };\n    int *p = (int *)(a + 1);\n    printf(\"%d\", *(p + 3));\n    return 0;\n}\n\nWhat integer value is printed by the program?",
        "options": None,
        "answer": "8",
        "msq_answers": None,
        "explanation": "Let's trace the pointer arithmetic:\n1. 'a' is a 2D array of size 3x4.\n2. 'a + 1' points to the 1st row (0-indexed), which is the subarray {5, 6, 7, 8}.\n3. '(int *)(a + 1)' casts this row pointer into a simple pointer to the first integer of row 1, i.e., address of 5 (a[1][0]).\n4. 'p + 3' advances 3 integers forward: p[0]=5, p[1]=6, p[2]=7, p[3]=8.\n5. Therefore, *(p + 3) yields 8.",
        "gate_trap": "Watch out for pointer type scaling: 'a + 1' advances by sizeof(int[4]) = 16 bytes, but '(int *)' causes subsequent '+ 3' to advance by 3 * sizeof(int) = 12 bytes.",
        "key_concept": "In C, a[i][j] = *(*(a + i) + j). Casting changes the scaling factor for pointer addition.",
        "reference_url": "https://www.geeksforgeeks.org/pointer-array-c/"
    },
    {
        "id": "ds_stack_001",
        "subject": "Programming & Data Structures",
        "topic": "Linear Data Structures",
        "subtopic": "Stacks & Applications (Infix/Postfix)",
        "concept": "Permutations obtainable using a single stack",
        "type": "MCQ",
        "marks": 1,
        "difficulty": "medium",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "The elements 1, 2, 3, 4, 5 are pushed onto a stack in that order. Elements can be popped at any time. Which of the following output permutation CANNOT be obtained?",
        "options": {
            "A": "3, 4, 5, 2, 1",
            "B": "1, 5, 4, 3, 2",
            "C": "2, 4, 1, 3, 5",
            "D": "3, 1, 2, 4, 5"
        },
        "answer": "D",
        "msq_answers": None,
        "explanation": "Let's test option D:\n- To get '3' first: Push 1, Push 2, Push 3, Pop 3. Stack now contains [1, 2] (top is 2).\n- Next output requires '1'. But top of stack is 2! To pop 1, we must pop 2 first. Hence '3, 1, 2...' is impossible.\n- General forbidden pattern: A permutation cannot contain subsequence '3 ... 1 ... 2' (312 pattern where larger elements were pushed later).",
        "gate_trap": "In any stack-sortable permutation, for any three elements i < j < k with i pushed first, the pattern k followed by i followed by j (where k > j > i) is impossible without j being popped before i.",
        "key_concept": "A permutation is stack-realizable iff it avoids the 231 (or 312 in decreasing) forbidden permutation pattern.",
        "reference_url": "https://www.geeksforgeeks.org/stack-permutations-check-if-an-array-is-stack-permutation-of-other/"
    },
    {
        "id": "ds_bst_001",
        "subject": "Programming & Data Structures",
        "topic": "Non-Linear Data Structures",
        "subtopic": "Binary Search Trees (BST)",
        "concept": "Valid BST search sequences and bounds checking",
        "type": "MSQ",
        "marks": 2,
        "difficulty": "gate",
        "source": "GATE-STYLE",
        "pyq_year": None,
        "q": "Suppose that we are searching for the key 42 in a Binary Search Tree (BST) containing distinct integers. Which of the following sequence(s) of nodes visited could CANNOT be a valid BST search sequence?\n\nSelect all that apply:",
        "options": {
            "A": "10, 75, 20, 60, 30, 50, 42",
            "B": "90, 12, 80, 25, 70, 35, 42",
            "C": "2, 40, 60, 45, 38, 42",
            "D": "5, 80, 20, 70, 22, 65, 42"
        },
        "answer": "C",
        "msq_answers": ["C"],
        "explanation": "Valid BST search maintaining allowable interval [low, high] for target 42:\n- A: [10,75]->20 in [10,75]->60 in [20,75]->30 in [20,60]->50 in [30,60]->42 in [30,50]. Valid!\n- B: [90]->[12,90]->[12,80]->[25,80]->[25,70]->[35,70]->42 in [35,70]. Valid!\n- C: 2 (interval [2, inf]) -> 40 (interval [40, inf]) -> 60 (interval [40, 60]) -> 45 (interval [40, 45]) -> 38. But 38 < 40, which violates the lower bound 40 established earlier! Invalid!\n- D: [5]->[5,80]->[20,80]->[20,70]->[22,70]->[22,65]->42 in [22,65]. Valid!\nTherefore, C cannot be a valid search sequence.",
        "gate_trap": "Track the tightening (low, high) open intervals at every branching decision. Any visited node falling outside previously set bounds is invalid.",
        "key_concept": "Every right turn sets a new lower bound; every left turn sets a new upper bound.",
        "reference_url": "https://www.geeksforgeeks.org/check-if-given-sorted-sub-sequence-exists-in-binary-search-tree/"
    }
]
